[package]
name = "pos"
version = "0.1.0"
description = "Offline-first supermarket POS desktop application"
authors = ["Ahmed Helmy"]
edition = "2021"

[lib]
name = "pos_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[[bin]]
name = "pos"
path = "src/main.rs"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
tauri-plugin-shell = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[profile.dev]
incremental = true

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
strip = true
